import os


POSTGRES_USER = os.getenv("POSTGRES_USER", "car_user")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "car_pass")
POSTGRES_DB = os.getenv("POSTGRES_DB", "car_research")
POSTGRES_HOST = os.getenv("POSTGRES_HOST", "db")
POSTGRES_PORT = os.getenv("POSTGRES_PORT", "5432")

DATABASE_URL = (
    f"postgresql+psycopg2://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
)

SOURCE_NAME = os.getenv("WORKER_SOURCE", "carsensor")

CARSENSOR_BASE_URL = os.getenv("CARSENSOR_BASE_URL", "https://carsensor.net").rstrip("/")
CARSENSOR_ROBOTS_URL = os.getenv("CARSENSOR_ROBOTS_URL", f"{CARSENSOR_BASE_URL}/robots.txt")
CARSENSOR_SITEMAP_INDEX_URL = os.getenv("CARSENSOR_SITEMAP_INDEX_URL", f"{CARSENSOR_BASE_URL}/usedcar-detail-index.xml")

WORKER_RUN_ONCE = os.getenv("WORKER_RUN_ONCE", "0") == "1"
INTERVAL_SECONDS = int(os.getenv("INTERVAL_SECONDS", os.getenv("SCRAPER_INTERVAL_SECONDS", "3600")))
CONCURRENCY = int(os.getenv("CONCURRENCY", os.getenv("WORKER_CONCURRENCY", "2")))

MAX_SITEMAPS = int(os.getenv("MAX_SITEMAPS", os.getenv("WORKER_MAX_SITEMAPS_PER_CYCLE", "20")))
POOL_SIZE = int(os.getenv("POOL_SIZE", os.getenv("WORKER_DISCOVERY_POOL_SIZE", "2000")))
MAX_LISTINGS = int(os.getenv("MAX_LISTINGS", os.getenv("WORKER_MAX_LISTINGS_PER_CYCLE", "400")))
PER_MAKE_LIMIT = int(os.getenv("PER_MAKE_LIMIT", "3"))
URLS_PER_SITEMAP = int(os.getenv("URLS_PER_SITEMAP", "400"))

BATCH_PAUSE = float(os.getenv("BATCH_PAUSE", os.getenv("WORKER_BATCH_PAUSE_SECONDS", "1.5")))
SCRAPE_TRIGGER_POLL_SECONDS = int(os.getenv("SCRAPE_TRIGGER_POLL_SECONDS", "10"))
MAX_RETRIES = int(os.getenv("MAX_RETRIES", os.getenv("WORKER_MAX_RETRIES", "5")))
BACKOFF_SECONDS = float(os.getenv("BACKOFF_SECONDS", os.getenv("WORKER_BACKOFF_SECONDS", "1.5")))
BACKOFF_JITTER_SECONDS = float(os.getenv("BACKOFF_JITTER_SECONDS", os.getenv("WORKER_BACKOFF_JITTER_SECONDS", "0.6")))
REQUEST_CONNECT_TIMEOUT_SECONDS = float(
    os.getenv("REQUEST_CONNECT_TIMEOUT_SECONDS", os.getenv("WORKER_REQUEST_CONNECT_TIMEOUT_SECONDS", "10"))
)
REQUEST_READ_TIMEOUT_SECONDS = float(
    os.getenv("REQUEST_READ_TIMEOUT_SECONDS", os.getenv("WORKER_REQUEST_READ_TIMEOUT_SECONDS", "20"))
)
REQUEST_DELAY_SECONDS = float(os.getenv("REQUEST_DELAY_SECONDS", os.getenv("WORKER_REQUEST_DELAY_SECONDS", "0.25")))

INACTIVE_AFTER_DAYS = int(os.getenv("INACTIVE_AFTER_DAYS", os.getenv("WORKER_INACTIVE_AFTER_DAYS", "7")))
DELETE_AFTER_DAYS = int(os.getenv("DELETE_AFTER_DAYS", os.getenv("WORKER_DELETE_AFTER_DAYS", "90")))
UPSERT_BATCH_SIZE = int(os.getenv("UPSERT_BATCH_SIZE", os.getenv("WORKER_UPSERT_BATCH_SIZE", "200")))

JPY_TO_RUB_RATE = float(os.getenv("JPY_TO_RUB_RATE", "0.62"))
